import type { Metadata } from "next";
import Link from "next/link";
import { OmniLogo } from "@/components/ui/omni-logo";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Omni OS terms of service.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <nav className="fixed top-0 w-full z-50 bg-white border-b border-surface-100">
        <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2.5">
            <OmniLogo size={32} className="text-surface-900" />
            <span className="font-display font-bold text-lg text-surface-900 tracking-tight">Omni OS</span>
          </Link>
          <Link href="/auth?mode=signup" className="btn-primary">Get Started</Link>
        </div>
      </nav>

      <section className="pt-32 pb-20 px-6">
        <div className="max-w-3xl mx-auto">
          <div className="mono-label mb-3">Legal</div>
          <h1 className="font-display font-bold text-3xl text-surface-900 mb-2">Terms of Service</h1>
          <p className="text-sm text-surface-400 mb-10">Last updated: March 2026</p>

          <div className="space-y-8 text-sm text-surface-600 leading-relaxed">
            <div>
              <h2 className="font-semibold text-surface-900 text-base mb-2">1. Acceptance</h2>
              <p>By accessing Omni OS, you agree to these terms. If you do not agree, do not use the platform.</p>
            </div>
            <div>
              <h2 className="font-semibold text-surface-900 text-base mb-2">2. Service Description</h2>
              <p>Omni OS provides AI-powered business automation through autonomous agents. Agents execute tasks using third-party APIs configured by you. We are not responsible for the accuracy of AI-generated outputs or actions taken by agents on your behalf.</p>
            </div>
            <div>
              <h2 className="font-semibold text-surface-900 text-base mb-2">3. Your Responsibilities</h2>
              <p>You are responsible for: (a) the accuracy of your business profile, (b) API keys and credentials you provide, (c) reviewing and approving agent actions in guided mode, (d) compliance with applicable laws regarding automated outreach, marketing, and data processing.</p>
            </div>
            <div>
              <h2 className="font-semibold text-surface-900 text-base mb-2">4. Billing</h2>
              <p>Subscriptions are billed monthly. Early access pricing is guaranteed for 12 months from signup. You may cancel at any time; access continues until the end of your billing period.</p>
            </div>
            <div>
              <h2 className="font-semibold text-surface-900 text-base mb-2">5. AI Limitations</h2>
              <p>AI agents may produce inaccurate, incomplete, or inappropriate outputs. You should review all agent outputs before relying on them for business decisions. Omni OS is not liable for losses resulting from AI-generated content or actions.</p>
            </div>
            <div>
              <h2 className="font-semibold text-surface-900 text-base mb-2">6. Intellectual Property</h2>
              <p>You retain ownership of all content generated by agents on your behalf. Omni OS retains ownership of the platform, agent logic, and underlying technology.</p>
            </div>
            <div>
              <h2 className="font-semibold text-surface-900 text-base mb-2">7. Termination</h2>
              <p>We may suspend or terminate accounts that violate these terms, engage in spam, or use the platform for illegal activities.</p>
            </div>
            <div>
              <h2 className="font-semibold text-surface-900 text-base mb-2">8. Contact</h2>
              <p>For questions about these terms, contact legal@omnios.ai.</p>
            </div>
          </div>
        </div>
      </section>

      <footer className="border-t border-surface-100 py-10 px-6">
        <div className="max-w-6xl mx-auto flex items-center justify-between text-xs text-surface-400">
          <span>&copy; {new Date().getFullYear()} Omni OS Inc.</span>
          <div className="flex gap-6">
            <Link href="/" className="hover:text-surface-600">Home</Link>
            <Link href="/privacy" className="hover:text-surface-600">Privacy</Link>
            <Link href="/security" className="hover:text-surface-600">Security</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
